/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginController;
import controller.ProcesarMovimientosDeCuentaDeEmpresa;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.tree.TreePath;
import model.TipoUsuario;

/**
 *
 * @author Ariel
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private ProcesarMovimientosDeCuentaDeEmpresa controlador;
    
    private TipoUsuario tipoUsuario = null;
    
    private PanelEmpresa unPanelEmpresa;
    private PanelEmpleado unPanelEmpleado;
    private PanelUsuario unPanelUsuario;
    private PanelSeleccionDeCuentas unPanelSeleccionDeCuenta;

    /**
     * captura la seleccion en el arbol
     */
    String captura = null;

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        
        
        
        //Carga Icono de la empresa
        try {
            //Icono de la aplicacion
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());

        } catch (Exception e) {
        }
        initComponents();
        this.setSize(1200, 750);
        this.setTitle("Aplicacion de Tesoreria");
        this.getContentPane().setBackground(new Color(89, 97, 106));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneArbol = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_TipoUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_puesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1330, 850));
        setMinimumSize(new java.awt.Dimension(1330, 850));
        setPreferredSize(new java.awt.Dimension(1330, 870));
        setResizable(false);

        jPanelArbol.setBackground(new java.awt.Color(255, 153, 51));
        jPanelArbol.setMaximumSize(new java.awt.Dimension(350, 750));
        jPanelArbol.setMinimumSize(new java.awt.Dimension(350, 750));
        jPanelArbol.setPreferredSize(new java.awt.Dimension(350, 750));

        jScrollPaneArbol.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPaneArbol.setBorder(null);
        jScrollPaneArbol.setAlignmentX(0.0F);
        jScrollPaneArbol.setAlignmentY(0.0F);
        jScrollPaneArbol.setMaximumSize(new java.awt.Dimension(350, 750));
        jScrollPaneArbol.setMinimumSize(new java.awt.Dimension(350, 750));
        jScrollPaneArbol.setPreferredSize(new java.awt.Dimension(350, 750));

        arbolModulos.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        arbolModulos.setForeground(new java.awt.Color(255, 255, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Empresa");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Administración General");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresa");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empleados");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuarios");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Modulo de Contabilidad");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Registrar Movimientos");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbolModulos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolModulos.setAlignmentX(0.0F);
        arbolModulos.setAlignmentY(0.0F);
        arbolModulos.setMaximumSize(new java.awt.Dimension(330, 750));
        arbolModulos.setMinimumSize(new java.awt.Dimension(330, 750));
        arbolModulos.setName(""); // NOI18N
        arbolModulos.setPreferredSize(new java.awt.Dimension(330, 750));
        arbolModulos.setShowsRootHandles(true);
        arbolModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolModulosMouseClicked(evt);
            }
        });
        jScrollPaneArbol.setViewportView(arbolModulos);

        javax.swing.GroupLayout jPanelArbolLayout = new javax.swing.GroupLayout(jPanelArbol);
        jPanelArbol.setLayout(jPanelArbolLayout);
        jPanelArbolLayout.setHorizontalGroup(
            jPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArbolLayout.createSequentialGroup()
                .addComponent(jScrollPaneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelArbolLayout.setVerticalGroup(
            jPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArbolLayout.createSequentialGroup()
                .addComponent(jScrollPaneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelContenido.setBackground(new java.awt.Color(95, 212, 175));
        jPanelContenido.setAlignmentX(0.0F);
        jPanelContenido.setAlignmentY(0.0F);
        jPanelContenido.setAutoscrolls(true);
        jPanelContenido.setMaximumSize(new java.awt.Dimension(950, 750));
        jPanelContenido.setMinimumSize(new java.awt.Dimension(950, 750));
        jPanelContenido.setName(""); // NOI18N
        jPanelContenido.setPreferredSize(new java.awt.Dimension(950, 750));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background2.fw.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(255, 149, 84));
        jPanel3.setMaximumSize(new java.awt.Dimension(1342, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(1342, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(1342, 60));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 97, 106));
        jLabel1.setText("USUARIO:");

        jlbl_usuario.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jlbl_usuario.setForeground(new java.awt.Color(89, 97, 106));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(89, 97, 106));
        jLabel3.setText("TIPO USUARIO");

        jlbl_TipoUsuario.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jlbl_TipoUsuario.setForeground(new java.awt.Color(89, 97, 106));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(89, 97, 106));
        jLabel5.setText("TIPO EMPLEADO");

        jlbl_puesto.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jlbl_puesto.setForeground(new java.awt.Color(89, 97, 106));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbl_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbl_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlbl_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_TipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_usuario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arbolModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolModulosMouseClicked

        if (arbolModulos.isEnabled()) {
            TreePath tp = arbolModulos.getPathForLocation(evt.getX(), evt.getY());
            if (tp != null) {
                captura = arbolModulos.getSelectionPath().toString();
                /*Intentanmos validar si la cadena equivale a vacio.
                Si ejecutamos nos daremos cuenta que esto
                genera una excepciòn ya que la cadena es nula*/

                if (captura.equals("[Empresa, Administración General, Empresa]")) {

                    habilitarArbol(false);
                    
                    //Se crea el Panel Emplesa
                    this.unPanelEmpresa = new PanelEmpresa();
                    this.unPanelEmpresa.setSize(950, 750);
                    this.unPanelEmpresa.setVisible(true);

                    this.jPanelContenido.add(this.unPanelEmpresa);
                    this.unPanelEmpresa.validate();

                }

                if (captura.equals("[Empresa, Administración General, Empleados]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Empleado
                    this.unPanelEmpleado = new PanelEmpleado();
                    this.unPanelEmpleado.setSize(950, 750);
                    this.unPanelEmpleado.setVisible(true);

                    this.jPanelContenido.add(this.unPanelEmpleado);

                    this.unPanelEmpleado.validate();
                }

                if (captura.equals("[Empresa, Administración General, Usuarios]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelUsuario = new PanelUsuario();
                    this.unPanelUsuario.setSize(950, 750);
                    this.unPanelUsuario.setVisible(true);

                    this.jPanelContenido.add(this.unPanelUsuario);

                    this.unPanelUsuario.validate();
                }
                
                if (captura.equals("[Empresa, Modulo de Contabilidad, Registrar Movimientos]")) {
                    
                    this.controlador = new ProcesarMovimientosDeCuentaDeEmpresa();
                    habilitarArbol(false);

                    
                    //Se crea el Panel Emplesa
                    this.unPanelSeleccionDeCuenta = new PanelSeleccionDeCuentas(this.controlador);
                    this.unPanelSeleccionDeCuenta.setSize(950, 750);
                    this.unPanelSeleccionDeCuenta.setVisible(true);

                    this.jPanelContenido.add(this.unPanelSeleccionDeCuenta);

                    this.unPanelSeleccionDeCuenta.validate();
                }
                

            }
        }
    }//GEN-LAST:event_arbolModulosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTree arbolModulos = new javax.swing.JTree();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    public static final javax.swing.JPanel jPanelArbol = new javax.swing.JPanel();
    public static final javax.swing.JPanel jPanelContenido = new javax.swing.JPanel();
    private javax.swing.JScrollPane jScrollPaneArbol;
    private javax.swing.JLabel jlbl_TipoUsuario;
    private javax.swing.JLabel jlbl_puesto;
    private javax.swing.JLabel jlbl_usuario;
    // End of variables declaration//GEN-END:variables

    public void arranca() {
        this.tipoUsuario = LoginController.getInstanceUsuario().getTipoUsuario();

        if (this.tipoUsuario != null) {
            if (this.tipoUsuario.getDescripcion().equals("Persona")) {
                JOptionPane.showMessageDialog(this, "Los Cliente solo pueden ingresar por la web");
                System.exit(0);
            }

            if (this.tipoUsuario.getDescripcion().equals("Empleado")) {
                //Si el usuario posee un empleado asociado
                if (LoginController.getInstanceUsuario().getUnEmpleado() != null) {

                    //Uso del Singleton creado en el Login
                    this.jlbl_usuario.setText(LoginController.getInstanceUsuario().getNombre());
                    this.jlbl_TipoUsuario.setText(LoginController.getInstanceUsuario().getTipoUsuario().getDescripcion());
                    this.jlbl_puesto.setText(LoginController.getInstanceUsuario().getUnEmpleado().getUnTipoEmpleado().getDescripcion());

                    jPanelContenido.repaint();
                    setLocationRelativeTo(null);// centra la ventana en la pantalla
                    setVisible(true);// visualiza la ventana
                    //default title and icon
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario es de tipo empleado, pero no tiene empleado asociado. Contacte con el Administrador");
                    System.exit(0);
                }
            }
        }
    }

    /**
     * Se llama desde cualquier lugar de la aplicación y bloqueara o habilitara
     * el arbol
     *
     * @param estado
     */
    private void habilitarArbol(boolean estado) {
        this.arbolModulos.setEnabled(estado);
        this.jPanelArbol.setEnabled(estado);
        this.jPanelArbol.repaint();
        this.jPanelArbol.validate();

        this.jPanelContenido.removeAll();
        this.jPanelContenido.repaint();
        this.jPanelContenido.validate();

        this.repaint();
        this.validate();
    }

    public static javax.swing.JPanel getjPanelArbol() {
        return jPanelArbol;
    }

    public static javax.swing.JPanel getjPanelContenido() {
        return jPanelContenido;
    }

    public static javax.swing.JTree getArbolModulos() {
        return arbolModulos;
    }

}
