/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProcesarMovimientosDeCuentaDeEmpresa;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import model.Concepto;
import model.LineaDeMovimiento;

/**
 *
 * @author Ariel
 */
public class PanelAgregarMovimiento extends javax.swing.JPanel implements InterfacePanel {

    //variables de comboBox
    private DefaultComboBoxModel conceptosModel;

    private final ValidadorDeCampos validador;

    private ProcesarMovimientosDeCuentaDeEmpresa controlador;

    private Concepto conceptoSeleccionado;

    /**
     * Creates new form PanelEmpresa
     *
     * @param controlador
     */
    public PanelAgregarMovimiento(ProcesarMovimientosDeCuentaDeEmpresa controlador) {

        //JComboBox vacio
        this.conceptosModel = new DefaultComboBoxModel();

        initComponents();
        btn_gp_tipoDeMovimiento.add(jrb_Debito);
        btn_gp_tipoDeMovimiento.add(jrb_Credito);

        validador = new ValidadorDeCampos();
        habilitarTodosLosBotones(true);
        this.controlador = controlador;

        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.RED, Color.WHITE, null, null);
        
        this.validador.validarNumeroDecimales(jtf_monto);
        this.validador.LimitarCaracteres(jtf_monto, 10);

        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setStringPainted(true);
        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setString("Seleccionar Cuenta y Fecha");
        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setValue(20);
        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setForeground(new Color(220, 118, 51));

        this.jlbl_titulo.setBackground(Color.BLACK);
        this.jlbl_titulo.setOpaque(true);

        this.jcb_concepto.setModel(conceptosModel);

        cargarConceptos();
        this.conceptoSeleccionado = null;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_gp_tipoDeMovimiento = new javax.swing.ButtonGroup();
        jPanelProgreso = new javax.swing.JPanel();
        jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa = new javax.swing.JProgressBar();
        jlbl_titulo = new javax.swing.JLabel();
        jPanel_Contenido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_concepto = new javax.swing.JComboBox<>();
        jtf_monto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrb_Credito = new javax.swing.JRadioButton();
        jrb_Debito = new javax.swing.JRadioButton();
        jbtn_aceptar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 750));
        setMinimumSize(new java.awt.Dimension(950, 750));
        setPreferredSize(new java.awt.Dimension(950, 750));

        jlbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_titulo.setText("PROCESAR MOVIMIENTOS DE CUENTAS DE EMPRESA");

        javax.swing.GroupLayout jPanelProgresoLayout = new javax.swing.GroupLayout(jPanelProgreso);
        jPanelProgreso.setLayout(jPanelProgresoLayout);
        jPanelProgresoLayout.setHorizontalGroup(
            jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                    .addComponent(jlbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProgresoLayout.setVerticalGroup(
            jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProgresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Contenido.setMaximumSize(new java.awt.Dimension(930, 460));
        jPanel_Contenido.setMinimumSize(new java.awt.Dimension(930, 460));
        jPanel_Contenido.setPreferredSize(new java.awt.Dimension(930, 460));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("CONCEPTO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("MONTO");

        jcb_concepto.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jcb_concepto.setModel(conceptosModel);
        jcb_concepto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_conceptoItemStateChanged(evt);
            }
        });

        jtf_monto.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jtf_monto.setEnabled(false);
        jtf_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_montoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("TIPO DE MOVIMIENTO");

        jrb_Credito.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jrb_Credito.setText("Credito");
        jrb_Credito.setEnabled(false);

        jrb_Debito.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jrb_Debito.setText("Debito");
        jrb_Debito.setEnabled(false);

        javax.swing.GroupLayout jPanel_ContenidoLayout = new javax.swing.GroupLayout(jPanel_Contenido);
        jPanel_Contenido.setLayout(jPanel_ContenidoLayout);
        jPanel_ContenidoLayout.setHorizontalGroup(
            jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcb_concepto, 0, 460, Short.MAX_VALUE)
                        .addComponent(jtf_monto))
                    .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                        .addComponent(jrb_Credito)
                        .addGap(68, 68, 68)
                        .addComponent(jrb_Debito)
                        .addGap(107, 107, 107)))
                .addGap(150, 150, 150))
        );
        jPanel_ContenidoLayout.setVerticalGroup(
            jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_concepto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_Credito)
                    .addComponent(jrb_Debito))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jbtn_aceptar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_aceptar.setText("ACEPTAR MOVIMIENTO");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });
        jbtn_aceptar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jbtn_aceptarPropertyChange(evt);
            }
        });

        jbtn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_cancelar.setText("CANCELAR MOVIMIENTO");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_aceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel_Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jbtn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        //Se crea el Panel Emplesa    
        PanelRegistroDeMovimientos unPanelRegistroDeMovimientos = new PanelRegistroDeMovimientos(this.controlador);
        unPanelRegistroDeMovimientos.setSize(950, 750);
        unPanelRegistroDeMovimientos.setLocation(0, 0);
        unPanelRegistroDeMovimientos.setVisible(true);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().add(unPanelRegistroDeMovimientos);
        JFramePrincipal.getjPanelContenido().repaint();
        JFramePrincipal.getjPanelContenido().validate();
        this.removeAll();
        this.updateUI();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    /**
     * Comenzar Nuevo registro de movimiento
     *
     * @param evt
     */
    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        LineaDeMovimiento nlrm = new LineaDeMovimiento(); 
        
        float montoAuxiliar = Float.parseFloat(jtf_monto.getText());
        nlrm.setMonto(montoAuxiliar);
        
        nlrm.setUnConcepto(conceptoSeleccionado);
        
        controlador.agregarNuevoRegistro(nlrm);
        
        //Se crea el Panel Emplesa    
        PanelRegistroDeMovimientos unPanelRegistroDeMovimientos = new PanelRegistroDeMovimientos(this.controlador);
        unPanelRegistroDeMovimientos.setSize(950, 750);
        unPanelRegistroDeMovimientos.setLocation(0, 0);
        unPanelRegistroDeMovimientos.setVisible(true);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().add(unPanelRegistroDeMovimientos);
        JFramePrincipal.getjPanelContenido().repaint();
        JFramePrincipal.getjPanelContenido().validate();
        this.updateUI();

    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    private void jbtn_aceptarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jbtn_aceptarPropertyChange

    }//GEN-LAST:event_jbtn_aceptarPropertyChange

    private void jcb_conceptoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_conceptoItemStateChanged
        this.conceptoSeleccionado = (Concepto) jcb_concepto.getSelectedItem();
        if (this.conceptoSeleccionado != null) {
            jtf_monto.setEnabled(true);
            if (conceptoSeleccionado.getUnTipoMovimiento().getDescripcion().equals("Credito")) {
                this.jrb_Credito.setSelected(true);
                this.jrb_Debito.setSelected(false);
            }
            if (conceptoSeleccionado.getUnTipoMovimiento().getDescripcion().equals("Debito")) {
                this.jrb_Credito.setSelected(false);
                this.jrb_Debito.setSelected(true);
            }
        }
        this.jrb_Credito.repaint();
        this.jrb_Debito.repaint();
    }//GEN-LAST:event_jcb_conceptoItemStateChanged

    private void jtf_montoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_montoKeyReleased
        if (this.jtf_monto.isEditable()) {
            if (!this.jtf_monto.getText().isEmpty()) {
                habilitarTodosLosBotones(true);
            }else{
                habilitarTodosLosBotones(false);
            }
        }
    }//GEN-LAST:event_jtf_montoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_gp_tipoDeMovimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelProgreso;
    private javax.swing.JPanel jPanel_Contenido;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JComboBox<String> jcb_concepto;
    private javax.swing.JLabel jlbl_titulo;
    private javax.swing.JProgressBar jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa;
    private javax.swing.JRadioButton jrb_Credito;
    private javax.swing.JRadioButton jrb_Debito;
    private javax.swing.JTextField jtf_monto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        //inhabilita campos
    }

    @Override
    public void limpiarTodosLosCampos() {
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        this.validador.habilitarBoton(estado, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
    }

    /**
     * Carga las Areas el el JComboBox Cuentas de Empresa
     *
     */
    public void cargarConceptos() {

        this.conceptosModel.removeAllElements();

        this.conceptosModel = new DefaultComboBoxModel();

        for (Concepto cuentasRecorrido : this.controlador.buscarTodosLosConceptos()) {
            conceptosModel.addElement(cuentasRecorrido);
        }

        this.jcb_concepto.setModel(this.conceptosModel);

        repaint();

    }

}
