/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProcesarMovimientosDeCuentaDeEmpresa;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import model.Cuenta;
import model.Empleado;
import model.LineaDeMovimiento;
import view.resources.TablaEmpleadoModelo;
import view.resources.TablaLineasDeMovimientoModelo;

/**
 *
 * @author Ariel
 */
public class PanelRegistroDeMovimientos extends javax.swing.JPanel implements InterfacePanel {

    private final ValidadorDeCampos validador;

    //variables de tabla
    private TablaLineasDeMovimientoModelo tablaLineaDeMovimientoModelo;

    //variables de comboBox
    private DefaultComboBoxModel cuentaModel;

    private ProcesarMovimientosDeCuentaDeEmpresa controlador;

    private List<LineaDeMovimiento> lineasDeMovimientos;

    /**
     * Creates new form PanelPersona
     *
     * @param controlador
     */
    public PanelRegistroDeMovimientos(ProcesarMovimientosDeCuentaDeEmpresa controlador) {
        //JTable vacio
        this.tablaLineaDeMovimientoModelo = new TablaLineasDeMovimientoModelo();
        this.validador = new ValidadorDeCampos();
        //JComboBox vacio
        this.cuentaModel = new DefaultComboBoxModel();

        this.lineasDeMovimientos = new ArrayList<>();
        initComponents();
        habilitarTodosLosBotones(false);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_generarInforme, new Color(30, 132, 73), Color.WHITE, null, null);

        habilitarTodosLosCampos(false);

        //iniciar el controladorPersona de esta vista
        this.controlador = controlador;
        setSize(800, 600);

        limpiarTodosLosCampos();

        this.validador.validarSoloLetras(jtf_fecha);
        this.validador.LimitarCaracteres(this.jtf_fecha, 30);
        this.validador.validarSoloLetras(jtf_saldo);
        this.validador.LimitarCaracteres(this.jtf_saldo, 30);

        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setStringPainted(true);
        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setString("Registrar Lineas de Movimiento");
        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setValue(60);
        this.jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa.setForeground(new Color(220, 118, 51));

        this.jlbl_titulo.setBackground(Color.BLACK);
        this.jlbl_titulo.setOpaque(true);

        cargarRegistroDeMovimientosActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProgreso = new javax.swing.JPanel();
        jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa = new javax.swing.JProgressBar();
        jlbl_titulo = new javax.swing.JLabel();
        jPanel_datos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_saldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb_cuenta = new javax.swing.JComboBox<>();
        jlbl_alertaNombre = new javax.swing.JLabel();
        jlbl_alertaApellido = new javax.swing.JLabel();
        jlbl_alertaDNI = new javax.swing.JLabel();
        jlbl_alertaTipoPersona = new javax.swing.JLabel();
        jPanel_crud = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jtb_lineasDeMovimientos = new javax.swing.JTable();
        jbtn_agregarMovimiento = new javax.swing.JButton();
        jbtn_generarInforme = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 750));
        setMinimumSize(new java.awt.Dimension(950, 750));
        setPreferredSize(new java.awt.Dimension(950, 750));

        jlbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_titulo.setText("PROCESAR MOVIMIENTOS DE CUENTAS DE EMPRESA");

        javax.swing.GroupLayout jPanelProgresoLayout = new javax.swing.GroupLayout(jPanelProgreso);
        jPanelProgreso.setLayout(jPanelProgresoLayout);
        jPanelProgresoLayout.setHorizontalGroup(
            jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelProgresoLayout.setVerticalGroup(
            jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProgresoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FECHA");

        jtf_fecha.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jtf_fecha.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SALDO");

        jtf_saldo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jtf_saldo.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CUENTA");

        jcb_cuenta.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jcb_cuenta.setModel(cuentaModel);

        jlbl_alertaNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbl_alertaApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbl_alertaDNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbl_alertaTipoPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_datosLayout = new javax.swing.GroupLayout(jPanel_datos);
        jPanel_datos.setLayout(jPanel_datosLayout);
        jPanel_datosLayout.setHorizontalGroup(
            jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosLayout.createSequentialGroup()
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(jlbl_alertaTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jcb_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datosLayout.createSequentialGroup()
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_datosLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jtf_saldo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_datosLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(440, 440, 440)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_alertaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_alertaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlbl_alertaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel_datosLayout.setVerticalGroup(
            jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosLayout.createSequentialGroup()
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbl_alertaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jlbl_alertaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jlbl_alertaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jlbl_alertaTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setPreferredSize(new java.awt.Dimension(950, 750));

        jtb_lineasDeMovimientos.setModel(tablaLineaDeMovimientoModelo);
        jScrollPaneTabla.setViewportView(jtb_lineasDeMovimientos);

        jbtn_agregarMovimiento.setText("Agregar Movimiento");
        jbtn_agregarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_crudLayout = new javax.swing.GroupLayout(jPanel_crud);
        jPanel_crud.setLayout(jPanel_crudLayout);
        jPanel_crudLayout.setHorizontalGroup(
            jPanel_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crudLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_crudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_agregarMovimiento)
                .addGap(57, 57, 57))
        );
        jPanel_crudLayout.setVerticalGroup(
            jPanel_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crudLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jbtn_agregarMovimiento)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jbtn_generarInforme.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_generarInforme.setText("GENERAR INFORME");
        jbtn_generarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_generarInformeActionPerformed(evt);
            }
        });

        jbtn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_cancelar.setText("CANCELAR REGISTRO");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProgreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_generarInforme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_crud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_crud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_generarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controla el boton volver
     *
     * @param evt
     */
    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed

        //Inhabilita Botones
        habilitarTodosLosBotones(false);

        //limpia todos los campos
        limpiarTodosLosCampos();

        //Habilita el Arbol de seleccion
        JFramePrincipal.getArbolModulos().setEnabled(true);
        JFramePrincipal.getjPanelContenido().removeAll();

        this.controlador = null;
        this.removeAll();

        revalidate();
        repaint();

        JFramePrincipal.getjPanelContenido().repaint();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    /**
     * Controla el boton agregar
     *
     * @param evt
     */
    private void jbtn_generarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_generarInformeActionPerformed

        //this.controlador.getNuevoTurno().setUnEmpleado(empleadoSeleccionado);
        //Se crea el Panel Emplesa    
        //PanelProcesarTurno05 unPaneProcesarTurno05 = new PanelProcesarTurno05(this.controlador);
        //unPaneProcesarTurno05.setSize(950, 750);
        //unPaneProcesarTurno05.setLocation(0, 0);
        //unPaneProcesarTurno05.setVisible(true);
        //JFramePrincipal.modificarPanelContenido(unPanelProcesarTurno02);
        //JFramePrincipal.getjPanelContenido().removeAll();
        //JFramePrincipal.getjPanelContenido().add(unPaneProcesarTurno05);
        //JFramePrincipal.getjPanelContenido().repaint();
        //JFramePrincipal.getjPanelContenido().validate();

    }//GEN-LAST:event_jbtn_generarInformeActionPerformed

    private void jbtn_agregarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarMovimientoActionPerformed

        //Se crea el Panel Emplesa    
        PanelAgregarMovimiento unPanelAgregarMovimiento = new PanelAgregarMovimiento(this.controlador);
        unPanelAgregarMovimiento.setSize(950, 750);
        unPanelAgregarMovimiento.setLocation(0, 0);
        unPanelAgregarMovimiento.setVisible(true);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().add(unPanelAgregarMovimiento);
        JFramePrincipal.getjPanelContenido().repaint();
        JFramePrincipal.getjPanelContenido().validate();
        this.updateUI();
    }//GEN-LAST:event_jbtn_agregarMovimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelProgreso;
    private javax.swing.JPanel jPanel_crud;
    private javax.swing.JPanel jPanel_datos;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JButton jbtn_agregarMovimiento;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_generarInforme;
    private javax.swing.JComboBox<String> jcb_cuenta;
    private javax.swing.JLabel jlbl_alertaApellido;
    private javax.swing.JLabel jlbl_alertaDNI;
    private javax.swing.JLabel jlbl_alertaNombre;
    private javax.swing.JLabel jlbl_alertaTipoPersona;
    private javax.swing.JLabel jlbl_titulo;
    private javax.swing.JProgressBar jpb_estado_ProcesarMovimientosDeCuentaDeEmpresa;
    private javax.swing.JTable jtb_lineasDeMovimientos;
    private javax.swing.JTextField jtf_fecha;
    private javax.swing.JTextField jtf_saldo;
    // End of variables declaration//GEN-END:variables

    //--------------------------------------------------------------------------
    //--------------------------Metodos Implementados---------------------------
    //--------------------------------------------------------------------------
    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        this.validador.habilitarCampo(estado, this.jtf_fecha);
        this.validador.habilitarCampo(estado, this.jtf_saldo);
        this.validador.habilitarCombobox(estado, this.jcb_cuenta);
    }

    @Override
    public void limpiarTodosLosCampos() {
        this.validador.limpiarCampo(this.jtf_fecha);
        this.validador.limpiarCampo(this.jtf_saldo);
        this.jcb_cuenta.removeAllItems();
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        this.validador.habilitarBoton(estado, this.jbtn_generarInforme, new Color(30, 132, 73), Color.WHITE, null, null);
    }

    //--------------------------------------------------------------------------
    //--------------------------Metodos Getters y Settes------------------------
    //--------------------------------------------------------------------------
    public javax.swing.JButton getJbtn_agregar() {
        return this.jbtn_generarInforme;
    }

    public ValidadorDeCampos getValidador() {
        return this.validador;
    }

    public void cargarRegistroDeMovimientosActual() {

        //System.out.println(""+controlador.getRegistroSeleccionado().getUnaCuenta().getDescripcion());
        
        
        this.cuentaModel = new DefaultComboBoxModel();

        this.cuentaModel.addElement(controlador.getRegistroSeleccionado().getUnaCuenta());
        this.jcb_cuenta.setModel(this.cuentaModel);

        this.jtf_fecha.setText(this.validador.convertirFechaAString(controlador.getRegistroSeleccionado().getFecha()));
        this.jtf_saldo.setText("$ " + controlador.getRegistroSeleccionado().getSaldo());
        
        
        
        if (!controlador.getRegistroSeleccionado().getLineasDeRegistroDeMovimiento().isEmpty()) {
            this.tablaLineaDeMovimientoModelo.setLineasDeMovimientos(this.controlador.buscarTodasLasLineasDeMovimientoDeUnRegistro());
            //Refrescar el modelo en la tabla
            this.tablaLineaDeMovimientoModelo.fireTableDataChanged();
        }

    }

}
